name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Dashboard
        - API
        - HAL
        - Boot / First-run setup
        - Network modes
        - App Store
        - Installer (curl / Pi Imager)
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: CubeOS Version
      placeholder: "e.g. 0.2.0-beta.01"
    validations:
      required: true
  - type: dropdown
    id: hardware
    attributes:
      label: Hardware
      options:
        - Raspberry Pi 5
        - Raspberry Pi 4
        - x86_64 (Intel/AMD)
        - Other ARM64
        - Other
    validations:
      required: true
  - type: dropdown
    id: install_method
    attributes:
      label: Installation Method
      options:
        - Flashed with Raspberry Pi Imager
        - Flashed with dd / Etcher
        - curl installer
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1. Go to...\n2. Click...\n3. See error"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: "Paste logs from Dozzle or `docker service logs <name>`"
      render: shell
