name: Feature Request
description: Suggest an idea for CubeOS
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature address?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Dashboard
        - API
        - HAL
        - App Store
        - Network
        - Boot / Installer
        - Documentation
        - Other
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
